### PR TITLE
login signup modal

### PR DESCRIPTION
**Pull request by smcgovern-proj**
Hey all, 

Made some styling changes to login + made a modal popup if user wants to register instead of login. Avoided tweaking functionality/server requests since I figure @melikaxo is still working on that with google auth; changes are mostly cosmetic.

Modal should function for other applications too if you want to use it! Just pass it children the way you would any other html element.

Note: Still no checkbox or anything to mark whether user is a performer or not. Didn't want to mess with that since it's functionality and not UI.

### CODE REVIEW

**Review by Joshua-Barnes03 — APPROVED** [review]
*meant to be change request, editing*

**Review by Joshua-Barnes03 — CHANGES_REQUESTED** [review]
I'm impressed that the modal is so little code. However, can it be configured it dim everything else in the background? Additionally, I think it's a little small for a phone screen, is there a way we can increase it in size? Lastly, if you haven't already, looking into rounded corners for the modal might be good, I'm not sure I like the sharp edges.

**Review by melikaxo — APPROVED** [review]
looks good to me, previously agreed with josh's changes, thank you sean!

**Review by Joshua-Barnes03 — APPROVED** [review]
Appreciate those changes being made.

**Pull request merged**
