### PR TITLE
Hamburger menu

### PR DESCRIPTION
**Pull request by smcgovern-proj**
Hamburger menu that will eventually allow users to travel to different pages in the app. Currently, the a tag hrefs don't lead anywhere but I'll circle back to them after we set up client-side routing.

Right now it provides a hardcoded set of options, and the menu expands upwards. If there's a need for it in the future just let me know and I can refactor to take props that tell it whether to drop down/up or what the menu options should be.

### CODE REVIEW

**Review by melikaxo — APPROVED** [review]
looks good to me

**Review by Joshua-Barnes03 — APPROVED** [review]
Not code breaking but you're destructuring out Fragment specifically but I don't see it being used. Probably just a general practice you perform but if you don't need it, it's helpful for later reading to not have to figure out it's not being used.

Still approving though.

**Comment by smcgovern-proj** [comment]
Thanks for the reviews y'all. Will remove the Fragment import before merging.

**Review by clendon — APPROVED** [review]
Looks good to me. I agree with Josh about importing Fragment.

**Pull request merged**
