### PR TITLE
Map component resizing, styling

### PR DESCRIPTION
**Pull request by sumitz1207**
- Map resizing changes made so that it fills all screens, changes dynamically, and got footer/ menu reappearing.
- Get an error with "map undefined" when trying to navigate via the hamburger menu
- Hamburger menu does pop out over map but has a transparent background
- Need to get unique events markers displaying once the events arrays are added to server data.
- Always start in the middle of the Pacific Ocean despite having center property coordinates in New York.

### CODE REVIEW

**Review by haydenbp — CHANGES_REQUESTED** [review]
Seems to work fine except the center, whatever line 67 in src/Map/Map.jsx  does is what is messing it up, if you delete that line the initial center works.

67           onLoad={loadHandler}

**Comment by haydenbp** [comment]
image

street view is broke

**Comment by sumitz1207** [comment]
> image
> 
> street view is broke

hmm seems to work for me?
Screen Shot 2021-09-01 at 6 49 27 PM
Screen Shot 2021-09-01 at 6 51 17 PM

**Review by haydenbp — APPROVED** [review]
looks good, i refreshed and it works. my bad

**Pull request merged**
